config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  get '/category/:id' => "posts#categorized"
  resources :posts do
    resource :like, module: :posts
    resources :comments
  end

  resources :tags, only: [:index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :user
  has_one_attached :image
  acts_as_taggable_on :tags

  scope :with_tags, -> (tags) {tagged_with(tags, :any => true)}
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :assignments
  has_many :users, through: :assignments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  has_many :likes
  has_many :assignments
  has_many :roles, through: :assignments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def likes?(post)
    post.likes.where(user_id: id).any?
  end

  def admin?
    check_role(roles, ["admin"])
  end

  def author?(post, user)
    check_role(roles, ["admin"]) or (post.user_id == user.id and check_role(roles, ["author"]))
  end

  def subscriber?
    check_role(roles, ["subscriber"])
  end

  private

  def check_role(user_roles, roles_to_check)
     user_roles.map(&:name).any? {|r| roles_to_check.include?(r) } 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
  private

  def user_not_authorized(exception)
    policy_name = exception.policy.class.to_s.underscore

    flash[:error] = t "#{policy_name}.#{exception.query}", scope: "pundit", default: :default
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params.require(:comment).permit(:body))
    @comment.user_id = current_user.id
    if @comment.save
      respond_to do |format|
        format.html { redirect_to @post }
        format.js
      end
      # redirect_to @post
    else
      render :new
    end  
  end

  def delete
  end

  def destroy
  end
end

app/controllers/posts/likes_controller.rb
class Posts::LikesController <  ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @post.likes.where(user_id: current_user.id).first_or_create
    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  def destroy
    @post.likes.where(user_id: current_user.id).destroy_all
    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @post = authorize Post.find(params[:id])
    @comment = @post.comments.new
    @comments = @post.comments.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create!(post_params)
    authorize @post
    if @post.save
      redirect_to @post
    else
      render posts_path
    end
  end

  def categorized
    @posts = Post.with_tags(params[:id])
    render "categorized"
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
     @post = Post.find(params[:id])
     @post.update(params.require(:post).permit(:title, :description, :faves, :image))
    if @post.save
      redirect_to @post
    else
      render "edit"
    end
  end

  def delete
  end

  def destroy
  end

  private
  
  def post_params
    params.require(:post).permit(:title, :description, :faves, :image, :tag_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.js.erb
document.getElementById("comments").insertAdjacentHTML('beforeend', "<%=j render partial: "posts/comments/comment", locals: {comment: @comment}, format: :html %>")
document.getElementById('comment_body').value = "";

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/_nav.html.erb
    
  <div class="main-nav">
    <div class="main-nav__logo">
      <%= link_to "Cribbble", root_path %>
    </div>
    <!-- /.logo -->
    <div class="main-nav__menu">
      <ul>
        <li><a href="#">Explore</a></li>
        <li><a href="#">For Designers</a></li>
        <li><a href="#">Hiring Designers</a></li>
      </ul>
    </div>
    <!-- /.main-nav__menu -->
    <section class="actionables">
      <div class="search">
        <input type="text" name="search" id="search">
      </div>
      <!-- /.search -->
      <div class="upload">
        <%= link_to "Upload", new_post_path %>
      </div>
      <% if user_signed_in? %>
        <span class="current-user"><%= current_user.email %></span>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path %>
      <% end %>
      
      <!-- /.upload -->
    </section>
    <!-- /.actionables -->
  </div> <!-- /.main-nav -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cribbble</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: 'layouts/nav' %>
      <div class="container">
        <%= yield %>
      </div><!-- /.container -->
    </div><!-- /.container -->
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/posts/categorized.html.erb
<% @posts.each do |p| %>
  <%= image_tag p.image.variant(resize_to_limit: [250, 250]).processed.service_url %>
  <h3><%= link_to p.title, post_path(p.id) %></h3>
  <div><%= p.tag_list %></div>
<% end %>

app/views/posts/comments/_comment.html.erb
<p>(commenter: <%= comment.user.email %>) <%= comment.body %></p>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Create New Post</h1>

<%= form_with model: @post, class: "new-post" do |f| %>

    <% if @post.errors.any? %>
      <div class="form_error">
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%='Error: ' +  msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list, value: f.object.tag_list.to_s %>
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.submit %>
<% end %>
  

app/views/posts/index.html.erb
<ul>
  <li><%= link_to "All", '/' %></li>
  <li><%= link_to "Branding", '/category/branding' %></li>
  <li><%= link_to "Design", '/category/design' %></li>
</ul>
<div>
  <%= current_user.email %>
</div>

<% if !@posts.empty? %>
    <div class="cribbble-shots-grid">
      <% @posts.each do |p| %>
        <figure class="cribbble-shot">
          <%= image_tag p.image.variant(resize_to_limit: [250, 250]).processed.service_url %>
          <%= link_to p.title, post_path(p.id) %>
        </figure>
      <% end %>
    </div><!-- /.cribbble-shots-grid -->
<% end %>

app/views/posts/likes/_likes.html.erb
<% if user_signed_in? && current_user.likes?(@post) %>
    <%= link_to "Unlike", post_like_path(@post), method: :delete, remote: true %>
    <%= @post.likes.count %>
  <% else %>
    <%= link_to "Like", post_like_path(@post), method: :post, remote: true %>
    <%= @post.likes.count %>
<% end %>

app/views/posts/likes/create.js.erb
document.getElementById('likes').innerHTML = "<%=j render partial: "posts/likes/likes" %>"

app/views/posts/likes/destroy.js.erb
document.getElementById('likes').innerHTML = "<%=j render partial: "posts/likes/likes" %>"

app/views/posts/new.html.erb
<h1>Create New Post</h1>

<%= form_with model: @post, class: "new-post" do |f| %>

    <% if @post.errors.any? %>
      <div class="form_error">
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%='Error: ' +  msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list, value: f.object.tag_list.to_s %>
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.submit %>
<% end %>
  

app/views/posts/patch.html.erb
<h1>Posts#patch</h1>
<p>Find me in app/views/posts/patch.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts</h1>

<h3><%= @post.title %></h3>
<div id="likes">
  <%= render partial: "posts/likes/likes" %>
  
  <div class="actions">
    <%= link_to "Delete", post_path(@post), method: :delete %>
    <% if policy(@post).edit? %>
      <%= link_to "Edit", edit_post_path(@post) %>
    <% end %>
  </div><!-- /.actions -->


</div><!-- /#likes -->
<span>Uploaded by: <%= @post.user.email %></span>
<h3><%= @post.description %></h3>

<% if @post.image.attached? %>
  <%= image_tag @post.image.variant(resize_to_limit: [250, 250]).processed.service_url %>
<% end %>


<div class="comments">

<div id="comments"> 
  <% @comments.each do |c| %>        
    <%= render partial: "posts/comments/comment", locals: {comment: c} %>
  <% end %>
</div>


<h3>Comments</h3>
<%= form_with model: ([@post, @comment]) do |f| %>
    <%= f.text_area :body %>
    <%= f.submit %>
<% end %>
  
</div><!-- /.comments -->

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>